package org.protogalaxy.phss.component.file;


import java.util.Arrays;
import java.util.List;

public final class FileConsts {
    //Filesystem parts
    public static final String
            FILESYSTEM_MUSIC = "music",
            FILESYSTEM_ANIME = "anime",
            FILESYSTEM_MOVIE = "movie",
            FILESYSTEM_VIDEO = "video",
            FILESYSTEM_PHOTO = "photo",
            FILESYSTEM_ILLUSTRATION = "illustration",
            FILESYSTEM_DOCUMENT = "document",
            FILESYSTEM_BOOK = "book";
    //Document MIME types
    public static final String
            MIME_ADOBE_PDF = "application/pdf",
            MIME_ADOBE_PHOTOSHOP = "image/vnd.adobe.photoshop",
            MIME_MICROSOFT_WORD_OLD = "application/msword",
            MIME_MICROSOFT_EXCEL_OLD = "application/vnd.ms-excel",
            MIME_MICROSOFT_POWERPOINT_OLD = "application/vnd.ms-powerpoint",
            MIME_MICROSOFT_WORD = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            MIME_MICROSOFT_EXCEL = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            MIME_MICROSOFT_POWERPOINT = "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            MIME_OPENDOCUMENT_PRESENTATION = "application/vnd.oasis.opendocument.presentation",
            MIME_OPENDOCUMENT_SPREADSHEET = "application/vnd.oasis.opendocument.spreadsheet",
            MIME_OPENDOCUMENT_TEXT = "application/vnd.oasis.opendocument.text",
            MIME_MARKDOWN = "text/markdown",
            MIME_LATEX = "application/x-latex",
            MIME_EBOOK_IBOOKS = "application/x-ibooks+zip",
            MIME_EBOOK_EPUB = "application/epub+zip";
    //Audio metadata string
    public static final String
            METADATA_AUDIO_TITLE = "title",
            METADATA_AUDIO_ALBUM = "album",
            METADATA_AUDIO_ARTIST = "artist",
            METADATA_AUDIO_ALBUMARTIST = "album_artist",
            METADATA_AUDIO_COMPOSER = "composer",
            METADATA_AUDIO_PERFORMER = "performer",
            METADATA_AUDIO_DATE = "date",
            METADATA_AUDIO_TRACK = "track",
            METADATA_AUDIO_DISC = "disc",
            METADATA_AUDIO_GENRE = "genre",
            METADATA_AUDIO_PUBLISHER = "publisher",
            METADATA_AUDIO_COMMENT = "comment",
            METADATA_AUDIO_DURATION = "duration",
            METADATA_AUDIO_BITRATE = "bitrate",
            METADATA_AUDIO_SAMPLERATE = "sample_rate",
            METADATA_AUDIO_BITDEPTH = "bit_depth",
            METADATA_AUDIO_SIZE = "size",
            METADATA_AUDIO_COVER = "cover";
    //Book metadata string
    public static final String
            METADATA_BOOK_TITLE = "title",
            METADATA_BOOK_CREATED = "created",
            METADATA_BOOK_MODIFIED = "modified",
            METADATA_BOOK_PATH = "path",
            METADATA_BOOK_LASTACCESSTIME = "last_access",
            METADATA_BOOK_AUTHOR = "author",
            METADATA_BOOK_COVER = "cover",
            METADATA_BOOK_DATE = "date",
            METADATA_BOOK_DESCRIPTION = "description",
            METADATA_BOOK_CONTRIBUTOR = "contributor",
            METADATA_BOOK_PUBLISHER = "publisher",
            METADATA_BOOK_RIGHT = "right",
            METADATA_BOOK_LANGUAGE = "language",
            METADATA_BOOK_TYPE = "type";

    //Document metadata string
    public static final String
            METADATA_ADOBE_PDF_TITLE = "title",
            METADATA_ADOBE_PDF_CREATED = "created",
            METADATA_ADOBE_PDF_MODIFIED = "modified",
            METADATA_ADOBE_PDF_PATH = "path",
            METADATA_ADOBE_PDF_LASTACCESSTIME = "last_access",
            METADATA_ADOBE_PDF_CREATOR = "Author",
            METADATA_ADOBE_PDF_VERSION = "pdf:PDFVersion",
            METADATA_ADOBE_PDF_PRODUCER = "producer";
    public static final String
            METADATA_ADOBE_PHOTOSHOP_TITLE = "title",
            METADATA_ADOBE_PHOTOSHOP_CREATED = "created",
            METADATA_ADOBE_PHOTOSHOP_MODIFIED = "modified",
            METADATA_ADOBE_PHOTOSHOP_PATH = "path",
            METADATA_ADOBE_PHOTOSHOP_LASTACCESSTIME = "last_access",
            METADATA_ADOBE_PHOTOSHOP_WIDTH = "tiff:ImageWidth",
            METADATA_ADOBE_PHOTOSHOP_HEIGHT = "tiff:ImageLength",
            METADATA_ADOBE_PHOTOSHOP_COLORMODE = "photoshop:ColorMode",
            METADATA_ADOBE_PHOTOSHOP_BITSPERSAMPLE = "tiff:BitsPerSample";
    public static final String
            METADATA_MICROSOFT_WORD_OLD_TITLE = "title",
            METADATA_MICROSOFT_WORD_OLD_CREATED = "create_dtm",
            METADATA_MICROSOFT_WORD_OLD_MODIFIED = "last_save_dtm",
            METADATA_MICROSOFT_WORD_OLD_PATH = "path",
            METADATA_MICROSOFT_WORD_OLD_LASTACCESSTIME = "last_access",
            METADATA_MICROSOFT_WORD_OLD_CREATOR = "author",
            METADATA_MICROSOFT_WORD_OLD_MODIFIER = "last_author",
            METADATA_MICROSOFT_WORD_OLD_KEYWORDS = "keywords",
            METADATA_MICROSOFT_WORD_OLD_COMMENTS = "comments",
            METADATA_MICROSOFT_WORD_OLD_APPNAME = "app_name",
            METADATA_MICROSOFT_WORD_OLD_EDITTIME = "edit_time",
            METADATA_MICROSOFT_WORD_OLD_PAGECOUNT = "page_count",
            METADATA_MICROSOFT_WORD_OLD_WORDCOUNT = "word_count",
            METADATA_MICROSOFT_WORD_OLD_CHARCOUNT = "char_count",
            METADATA_MICROSOFT_WORD_OLD_LINECOUNT = "line_count",
            METADATA_MICROSOFT_WORD_OLD_PARCOUNT = "par_count";
    public static final String
            METADATA_MICROSOFT_EXCEL_OLD_TITLE = "title",
            METADATA_MICROSOFT_EXCEL_OLD_CREATED = "create_dtm",
            METADATA_MICROSOFT_EXCEL_OLD_MODIFIED = "last_save_dtm",
            METADATA_MICROSOFT_EXCEL_OLD_PATH = "path",
            METADATA_MICROSOFT_EXCEL_OLD_LASTACCESSTIME = "last_access",
            METADATA_MICROSOFT_EXCEL_OLD_CREATOR = "author",
            METADATA_MICROSOFT_EXCEL_OLD_MODIFIER = "last_author",
            METADATA_MICROSOFT_EXCEL_OLD_APPNAME = "app_name",
            METADATA_MICROSOFT_EXCEL_OLD_DOCPARTS = "doc_parts";
    public static final String
            METADATA_MICROSOFT_POWERPOINT_OLD_TITLE = "title",
            METADATA_MICROSOFT_POWERPOINT_OLD_CREATED = "create_dtm",
            METADATA_MICROSOFT_POWERPOINT_OLD_MODIFIED = "last_save_dtm",
            METADATA_MICROSOFT_POWERPOINT_OLD_PATH = "path",
            METADATA_MICROSOFT_POWERPOINT_OLD_LASTACCESSTIME = "last_access",
            METADATA_MICROSOFT_POWERPOINT_OLD_CREATOR = "author",
            METADATA_MICROSOFT_POWERPOINT_OLD_MODIFIER = "last_author",
            METADATA_MICROSOFT_POWERPOINT_OLD_APPNAME = "app_name",
            METADATA_MICROSOFT_POWERPOINT_OLD_EDITTIME = "edit_time",
            METADATA_MICROSOFT_POWERPOINT_OLD_WORDCOUNT = "word_count",
            METADATA_MICROSOFT_POWERPOINT_OLD_PRESFORMAT = "present_format",
            METADATA_MICROSOFT_POWERPOINT_OLD_BYTECOUNT = "byte_count",
            METADATA_MICROSOFT_POWERPOINT_OLD_PARCOUNT = "part_count",
            METADATA_MICROSOFT_POWERPOINT_OLD_SLIDECOUNT = "slide_count",
            METADATA_MICROSOFT_POWERPOINT_OLD_NOTECOUNT = "note_count",
            METADATA_MICROSOFT_POWERPOINT_OLD_HIDDENCOUNT = "hidden_count",
            METADATA_MICROSOFT_POWERPOINT_OLD_MMCLIPCOUNT = "mmclip_count";
    public static final String
            METADATA_MICROSOFT_WORD_TITLE = "title",
            METADATA_MICROSOFT_WORD_CREATED = "created",
            METADATA_MICROSOFT_WORD_MODIFIED = "modified",
            METADATA_MICROSOFT_WORD_PATH = "path",
            METADATA_MICROSOFT_WORD_LASTACCESSTIME = "last_access",
            METADATA_MICROSOFT_WORD_CREATOR = "creator",
            METADATA_MICROSOFT_WORD_MODIFIER = "modifier",
            METADATA_MICROSOFT_WORD_APPLICATION = "application",
            METADATA_MICROSOFT_WORD_APPVERSION = "app_version",
            METADATA_MICROSOFT_WORD_CHARACTERS = "characters",
            METADATA_MICROSOFT_WORD_CHARACTERSWITHSPACES = "characters_with_space",
            METADATA_MICROSOFT_WORD_LINES = "lines",
            METADATA_MICROSOFT_WORD_PAGES = "pages",
            METADATA_MICROSOFT_WORD_PARAGRAPHS = "paragraphs";
    public static final String
            METADATA_MICROSOFT_EXCEL_TITLE = "title",
            METADATA_MICROSOFT_EXCEL_CREATED = "created",
            METADATA_MICROSOFT_EXCEL_MODIFIED = "modified",
            METADATA_MICROSOFT_EXCEL_PATH = "path",
            METADATA_MICROSOFT_EXCEL_LASTACCESSTIME = "last_access",
            METADATA_MICROSOFT_EXCEL_CREATOR = "creator",
            METADATA_MICROSOFT_EXCEL_MODIFIER = "modifier",
            METADATA_MICROSOFT_EXCEL_APPLICATION = "application",
            METADATA_MICROSOFT_EXCEL_APPVERSION = "app_version",
            METADATA_MICROSOFT_EXCEL_CHARACTERS = "characters",
            METADATA_MICROSOFT_EXCEL_CHARACTERSWITHSPACES = "characters_with_spaces",
            METADATA_MICROSOFT_EXCEL_LINES = "lines",
            METADATA_MICROSOFT_EXCEL_PAGES = "pages",
            METADATA_MICROSOFT_EXCEL_PARAGRAPHS = "paragraphs";
    public static final String
            METADATA_MICROSOFT_POWERPOINT_TITLE = "title",
            METADATA_MICROSOFT_POWERPOINT_CREATED = "created",
            METADATA_MICROSOFT_POWERPOINT_MODIFIED = "modified",
            METADATA_MICROSOFT_POWERPOINT_PATH = "path",
            METADATA_MICROSOFT_POWERPOINT_LASTACCESSTIME = "last_access",
            METADATA_MICROSOFT_POWERPOINT_CREATOR = "creator",
            METADATA_MICROSOFT_POWERPOINT_MODIFIER = "last_modified_by",
            METADATA_MICROSOFT_POWERPOINT_APPLICATION = "application",
            METADATA_MICROSOFT_POWERPOINT_APPVERSION = "app_version",
            METADATA_MICROSOFT_POWERPOINT_CHARACTERS = "characters",
            METADATA_MICROSOFT_POWERPOINT_CHARACTERSWITHSPACES = "characters_with_spaces",
            METADATA_MICROSOFT_POWERPOINT_LINES = "lines",
            METADATA_MICROSOFT_POWERPOINT_PAGES = "pages",
            METADATA_MICROSOFT_POWERPOINT_PARAGRAPHS = "paragraphs",
            METADATA_MICROSOFT_POWERPOINT_PRESENTATIONFORMAT = "presentation_format";
    public static final String
            METADATA_OPENDOCUMENT_TEXT_TITLE = "dc:title",
            METADATA_OPENDOCUMENT_TEXT_CREATED = "meta:creation-date",
            METADATA_OPENDOCUMENT_TEXT_MODIFIED = "meta:save-date",
            METADATA_OPENDOCUMENT_TEXT_PATH = "path",
            METADATA_OPENDOCUMENT_TEXT_LASTACCESSTIME = "last_access",
            METADATA_OPENDOCUMENT_TEXT_CREATOR = "meta:initial-author",
            METADATA_OPENDOCUMENT_TEXT_MODIFIER = "meta:author",
            METADATA_OPENDOCUMENT_TEXT_WORDCOUNT = "meta:word-count",
            METADATA_OPENDOCUMENT_TEXT_CHARACTERCOUNT = "meta:character-count",
            METADATA_OPENDOCUMENT_TEXT_IMAGECOUNT = "meta:image-count",
            METADATA_OPENDOCUMENT_TEXT_PARCOUNT = "meta:paragraph-count",
            METADATA_OPENDOCUMENT_TEXT_TABLECOUNT = "meta:table-count",
            METADATA_OPENDOCUMENT_TEXT_PAGECOUNT = "meta:page-count";
    public static final String
            METADATA_OPENDOCUMENT_SPREADSHEET_TITLE = "dc:title",
            METADATA_OPENDOCUMENT_SPREADSHEET_CREATED = "meta:creation-date",
            METADATA_OPENDOCUMENT_SPREADSHEET_MODIFIED = "meta:save-date",
            METADATA_OPENDOCUMENT_SPREADSHEET_PATH = "path",
            METADATA_OPENDOCUMENT_SPREADSHEET_LASTACCESSTIME = "last_access",
            METADATA_OPENDOCUMENT_SPREADSHEET_CREATOR = "meta:initial-author",
            METADATA_OPENDOCUMENT_SPREADSHEET_MODIFIER = "meta:author";
    public static final String
            METADATA_OPENDOCUMENT_PRESENTATION_TITLE = "dc:title",
            METADATA_OPENDOCUMENT_PRESENTATION_CREATED = "meta:creation-date",
            METADATA_OPENDOCUMENT_PRESENTATION_MODIFIED = "meta:save-date",
            METADATA_OPENDOCUMENT_PRESENTATION_PATH = "path",
            METADATA_OPENDOCUMENT_PRESENTATION_LASTACCESSTIME = "last_access",
            METADATA_OPENDOCUMENT_PRESENTATION_CREATOR = "meta:initial-author",
            METADATA_OPENDOCUMENT_PRESENTATION_MODIFIER = "meta:author";
    //Audio metadata lists
    public static List<String> METADATA_AUDIO_STANDARD_LIST = Arrays.asList(
            METADATA_AUDIO_TITLE,
            METADATA_AUDIO_ALBUM,
            METADATA_AUDIO_ARTIST,
            METADATA_AUDIO_ALBUMARTIST,
            METADATA_AUDIO_COMPOSER,
            METADATA_AUDIO_PERFORMER,
            METADATA_AUDIO_DATE,
            METADATA_AUDIO_TRACK,
            METADATA_AUDIO_DISC,
            METADATA_AUDIO_GENRE,
            METADATA_AUDIO_PUBLISHER,
            METADATA_AUDIO_COMMENT
    );
    public static List<String> METADATA_AUDIO_FULL_LIST = Arrays.asList(
            METADATA_AUDIO_TITLE,
            METADATA_AUDIO_ALBUM,
            METADATA_AUDIO_ARTIST,
            METADATA_AUDIO_ALBUMARTIST,
            METADATA_AUDIO_COMPOSER,
            METADATA_AUDIO_PERFORMER,
            METADATA_AUDIO_DATE,
            METADATA_AUDIO_TRACK,
            METADATA_AUDIO_DISC,
            METADATA_AUDIO_GENRE,
            METADATA_AUDIO_PUBLISHER,
            METADATA_AUDIO_COMMENT,
            METADATA_AUDIO_DURATION,
            METADATA_AUDIO_BITRATE,
            METADATA_AUDIO_SAMPLERATE,
            METADATA_AUDIO_BITDEPTH,
            METADATA_AUDIO_SIZE,
            METADATA_AUDIO_COVER
    );
    //Book metadata Lists
    public static List<String> METADATA_BOOK_STANDARD_LIST = Arrays.asList(
            METADATA_BOOK_TITLE,
            METADATA_BOOK_CREATED,
            METADATA_BOOK_MODIFIED,
            METADATA_BOOK_PATH,
            METADATA_BOOK_LASTACCESSTIME,
            METADATA_BOOK_AUTHOR,
            METADATA_BOOK_DATE,
            METADATA_BOOK_DESCRIPTION,
            METADATA_BOOK_CONTRIBUTOR,
            METADATA_BOOK_PUBLISHER,
            METADATA_BOOK_RIGHT,
            METADATA_BOOK_LANGUAGE,
            METADATA_BOOK_TYPE
    );
    public static List<String> METADATA_BOOK_FULL_LIST = Arrays.asList(
            METADATA_BOOK_TITLE,
            METADATA_BOOK_CREATED,
            METADATA_BOOK_MODIFIED,
            METADATA_BOOK_PATH,
            METADATA_BOOK_LASTACCESSTIME,
            METADATA_BOOK_AUTHOR,
            METADATA_BOOK_COVER,
            METADATA_BOOK_DATE,
            METADATA_BOOK_DESCRIPTION,
            METADATA_BOOK_CONTRIBUTOR,
            METADATA_BOOK_PUBLISHER,
            METADATA_BOOK_RIGHT,
            METADATA_BOOK_LANGUAGE,
            METADATA_BOOK_TYPE
    );
    //Document metadata Lists
    public static final List<String> ADOBE_PDF_METADATA_LIST = Arrays.asList(
            METADATA_ADOBE_PDF_TITLE,
            METADATA_ADOBE_PDF_CREATED,
            METADATA_ADOBE_PDF_MODIFIED,
            METADATA_ADOBE_PDF_PATH,
            METADATA_ADOBE_PDF_LASTACCESSTIME,
            METADATA_ADOBE_PDF_CREATOR,
            METADATA_ADOBE_PDF_VERSION,
            METADATA_ADOBE_PDF_PRODUCER
    );
    public static final List<String> ADOBE_PHOTOSHOP_METADATA_LIST = Arrays.asList(
            METADATA_ADOBE_PHOTOSHOP_TITLE,
            METADATA_ADOBE_PHOTOSHOP_CREATED,
            METADATA_ADOBE_PHOTOSHOP_MODIFIED,
            METADATA_ADOBE_PHOTOSHOP_PATH,
            METADATA_ADOBE_PHOTOSHOP_LASTACCESSTIME,
            METADATA_ADOBE_PHOTOSHOP_WIDTH,
            METADATA_ADOBE_PHOTOSHOP_HEIGHT,
            METADATA_ADOBE_PHOTOSHOP_COLORMODE,
            METADATA_ADOBE_PHOTOSHOP_BITSPERSAMPLE
    );
    public static final List<String> MICROSOFT_WORD_OLD_METADATA_LIST = Arrays.asList(
            METADATA_MICROSOFT_WORD_OLD_TITLE,
            METADATA_MICROSOFT_WORD_OLD_CREATED,
            METADATA_MICROSOFT_WORD_OLD_MODIFIED,
            METADATA_MICROSOFT_WORD_OLD_PATH,
            METADATA_MICROSOFT_WORD_OLD_LASTACCESSTIME,
            METADATA_MICROSOFT_WORD_OLD_CREATOR,
            METADATA_MICROSOFT_WORD_OLD_MODIFIER,
            METADATA_MICROSOFT_WORD_OLD_KEYWORDS,
            METADATA_MICROSOFT_WORD_OLD_COMMENTS,
            METADATA_MICROSOFT_WORD_OLD_APPNAME,
            METADATA_MICROSOFT_WORD_OLD_EDITTIME,
            METADATA_MICROSOFT_WORD_OLD_PAGECOUNT,
            METADATA_MICROSOFT_WORD_OLD_WORDCOUNT,
            METADATA_MICROSOFT_WORD_OLD_CHARCOUNT,
            METADATA_MICROSOFT_WORD_OLD_LINECOUNT,
            METADATA_MICROSOFT_WORD_OLD_PARCOUNT
    );
    public static final List<String> MICROSOFT_EXCEL_OLD_METADATA_LIST = Arrays.asList(
            METADATA_MICROSOFT_EXCEL_OLD_TITLE,
            METADATA_MICROSOFT_EXCEL_OLD_CREATED,
            METADATA_MICROSOFT_EXCEL_OLD_MODIFIED,
            METADATA_MICROSOFT_EXCEL_OLD_PATH,
            METADATA_MICROSOFT_EXCEL_OLD_LASTACCESSTIME,
            METADATA_MICROSOFT_EXCEL_OLD_CREATOR,
            METADATA_MICROSOFT_EXCEL_OLD_MODIFIER,
            METADATA_MICROSOFT_EXCEL_OLD_APPNAME,
            METADATA_MICROSOFT_EXCEL_OLD_DOCPARTS
    );
    public static final List<String> MICROSOFT_POWERPOINT_OLD_METADATA_LIST = Arrays.asList(
            METADATA_MICROSOFT_POWERPOINT_OLD_TITLE,
            METADATA_MICROSOFT_POWERPOINT_OLD_CREATED,
            METADATA_MICROSOFT_POWERPOINT_OLD_MODIFIED,
            METADATA_MICROSOFT_POWERPOINT_OLD_PATH,
            METADATA_MICROSOFT_POWERPOINT_OLD_LASTACCESSTIME,
            METADATA_MICROSOFT_POWERPOINT_OLD_CREATOR,
            METADATA_MICROSOFT_POWERPOINT_OLD_MODIFIER,
            METADATA_MICROSOFT_POWERPOINT_OLD_APPNAME,
            METADATA_MICROSOFT_POWERPOINT_OLD_EDITTIME,
            METADATA_MICROSOFT_POWERPOINT_OLD_WORDCOUNT,
            METADATA_MICROSOFT_POWERPOINT_OLD_PRESFORMAT,
            METADATA_MICROSOFT_POWERPOINT_OLD_BYTECOUNT,
            METADATA_MICROSOFT_POWERPOINT_OLD_PARCOUNT,
            METADATA_MICROSOFT_POWERPOINT_OLD_SLIDECOUNT,
            METADATA_MICROSOFT_POWERPOINT_OLD_NOTECOUNT,
            METADATA_MICROSOFT_POWERPOINT_OLD_HIDDENCOUNT,
            METADATA_MICROSOFT_POWERPOINT_OLD_MMCLIPCOUNT
    );
    public static final List<String> MICROSOFT_WORD_METADATA_LIST = Arrays.asList(
            METADATA_MICROSOFT_WORD_TITLE,
            METADATA_MICROSOFT_WORD_CREATED,
            METADATA_MICROSOFT_WORD_MODIFIED,
            METADATA_MICROSOFT_WORD_PATH,
            METADATA_MICROSOFT_WORD_LASTACCESSTIME,
            METADATA_MICROSOFT_WORD_CREATOR,
            METADATA_MICROSOFT_WORD_MODIFIER,
            METADATA_MICROSOFT_WORD_APPLICATION,
            METADATA_MICROSOFT_WORD_APPVERSION,
            METADATA_MICROSOFT_WORD_CHARACTERS,
            METADATA_MICROSOFT_WORD_CHARACTERSWITHSPACES,
            METADATA_MICROSOFT_WORD_LINES,
            METADATA_MICROSOFT_WORD_PAGES,
            METADATA_MICROSOFT_WORD_PARAGRAPHS
    );
    public static final List<String> MICROSOFT_EXCEL_METADATA_LIST = Arrays.asList(
            METADATA_MICROSOFT_EXCEL_TITLE,
            METADATA_MICROSOFT_EXCEL_CREATED,
            METADATA_MICROSOFT_EXCEL_MODIFIED,
            METADATA_MICROSOFT_EXCEL_PATH,
            METADATA_MICROSOFT_EXCEL_LASTACCESSTIME,
            METADATA_MICROSOFT_EXCEL_CREATOR,
            METADATA_MICROSOFT_EXCEL_MODIFIER,
            METADATA_MICROSOFT_EXCEL_APPLICATION,
            METADATA_MICROSOFT_EXCEL_APPVERSION,
            METADATA_MICROSOFT_EXCEL_CHARACTERS,
            METADATA_MICROSOFT_EXCEL_CHARACTERSWITHSPACES,
            METADATA_MICROSOFT_EXCEL_LINES,
            METADATA_MICROSOFT_EXCEL_PAGES,
            METADATA_MICROSOFT_EXCEL_PARAGRAPHS
    );
    public static final List<String> MICROSOFT_POWERPOINT_METADATA_LIST = Arrays.asList(
            METADATA_MICROSOFT_POWERPOINT_TITLE,
            METADATA_MICROSOFT_POWERPOINT_CREATED,
            METADATA_MICROSOFT_POWERPOINT_MODIFIED,
            METADATA_MICROSOFT_POWERPOINT_PATH,
            METADATA_MICROSOFT_POWERPOINT_LASTACCESSTIME,
            METADATA_MICROSOFT_POWERPOINT_CREATOR,
            METADATA_MICROSOFT_POWERPOINT_MODIFIER,
            METADATA_MICROSOFT_POWERPOINT_APPLICATION,
            METADATA_MICROSOFT_POWERPOINT_APPVERSION,
            METADATA_MICROSOFT_POWERPOINT_CHARACTERS,
            METADATA_MICROSOFT_POWERPOINT_CHARACTERSWITHSPACES,
            METADATA_MICROSOFT_POWERPOINT_LINES,
            METADATA_MICROSOFT_POWERPOINT_PAGES,
            METADATA_MICROSOFT_POWERPOINT_PARAGRAPHS,
            METADATA_MICROSOFT_POWERPOINT_PRESENTATIONFORMAT
    );
    public static final List<String> OPENDOCUMENT_TEXT_METADATA_LIST = Arrays.asList(
            METADATA_OPENDOCUMENT_TEXT_TITLE,
            METADATA_OPENDOCUMENT_TEXT_CREATED,
            METADATA_OPENDOCUMENT_TEXT_MODIFIED,
            METADATA_OPENDOCUMENT_TEXT_PATH,
            METADATA_OPENDOCUMENT_TEXT_LASTACCESSTIME,
            METADATA_OPENDOCUMENT_TEXT_CREATOR,
            METADATA_OPENDOCUMENT_TEXT_MODIFIER,
            METADATA_OPENDOCUMENT_TEXT_WORDCOUNT,
            METADATA_OPENDOCUMENT_TEXT_CHARACTERCOUNT,
            METADATA_OPENDOCUMENT_TEXT_IMAGECOUNT,
            METADATA_OPENDOCUMENT_TEXT_PARCOUNT,
            METADATA_OPENDOCUMENT_TEXT_TABLECOUNT,
            METADATA_OPENDOCUMENT_TEXT_PAGECOUNT
    );
    public static final List<String> OPENDOCUMENT_SPREADSHEET_METADATA_LIST = Arrays.asList(
            METADATA_OPENDOCUMENT_SPREADSHEET_TITLE,
            METADATA_OPENDOCUMENT_SPREADSHEET_CREATED,
            METADATA_OPENDOCUMENT_SPREADSHEET_MODIFIED,
            METADATA_OPENDOCUMENT_SPREADSHEET_PATH,
            METADATA_OPENDOCUMENT_SPREADSHEET_LASTACCESSTIME,
            METADATA_OPENDOCUMENT_SPREADSHEET_CREATOR,
            METADATA_OPENDOCUMENT_SPREADSHEET_MODIFIER
    );
    public static final List<String> OPENDOCUMENT_SPREADSHEET_PRESENTATION_LIST = Arrays.asList(
            METADATA_OPENDOCUMENT_PRESENTATION_TITLE,
            METADATA_OPENDOCUMENT_PRESENTATION_CREATED,
            METADATA_OPENDOCUMENT_PRESENTATION_MODIFIED,
            METADATA_OPENDOCUMENT_PRESENTATION_PATH,
            METADATA_OPENDOCUMENT_PRESENTATION_LASTACCESSTIME,
            METADATA_OPENDOCUMENT_PRESENTATION_CREATOR,
            METADATA_OPENDOCUMENT_PRESENTATION_MODIFIER
    );
}
