spring:
  security:
    oauth2:
      client:
        registration:
          bangumi:
            client-id: bgm6165b9e794a763e1
            client-secret: 48aca6275eb4259de87406ec96120e34
            authorization-grant-type: authorization_code
            client-name: "bangumi"
        provider:
          bangumi:
            authorization-uri: https://bgm.tv/oauth/authorize
            token-uri: https://bgm.tv/oauth/access_token
            user-info-uri: https://bgm.tv/oauth/token_status